spring.application.name=bff-centro-mando
server.port=8082

jwt.secret=NaviumSuperSecretKeyParaFirmaDeTokens2026!

# URLS Dinámicas: Si existe la variable en Github la usa - Si no, usa el localhost por defecto
navium.api.contenedores.url=http://localhost:8080
navium.api.agendamientos.url=http://localhost:8085
navium.api.andenes.url=http://localhost:8083
