spring.application.name=bff-centro-mando
server.port=8082

springdoc.swagger-ui.path=/swagger-ui.html

# Clave Temporal para JWT (En producción, usar un vault o variable de entorno)
jwt.secret=NaviumSuperSecretKeyParaFirmaDeTokens2026!

# URLS Temporales
navium.api.contenedores.url=http://localhost:8080
navium.api.agendamientos.url=http://localhost:8085
navium.api.andenes.url=http://localhost:8083

# --- RESILIENCE4J CONFIGURATION ---

# Configuración de Timeouts (Ej: Si Agendamiento tarda más de 5 segundos, se corta)
resilience4j.timelimiter.instances.servicioAgendamiento.timeout-duration=5s
resilience4j.timelimiter.instances.servicioAndenes.timeout-duration=5s
resilience4j.timelimiter.instances.servicioContenedores.timeout-duration=5s

# Configuración del Circuit Breaker
# (Si falla el 50% de las peticiones, abre el circuito. Espera 10 seg en estado semi-abierto)
resilience4j.circuitbreaker.instances.servicioAgendamiento.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.servicioAgendamiento.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.servicioAgendamiento.sliding-window-size=10